// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIoS9JBjROZjeKI8SwV8M7_Db8dhVn4Xs',
    appId: '1:583163872183:web:d548048a13d8f5ffc39e32',
    messagingSenderId: '583163872183',
    projectId: 'souq-app-project',
    authDomain: 'souq-app-project.firebaseapp.com',
    databaseURL: 'https://souq-app-project-default-rtdb.asia-southeast1.firebasedatabase.app',
  storageBucket: 'souq-app-project.appspot.com',
    measurementId: 'G-SEETQQ99HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKxlyqzMRxIrrJ-4AtUlwPg86BPQtjfzU',
    appId: '1:583163872183:android:e3f889973fdaa08ac39e32',
    messagingSenderId: '583163872183',
    projectId: 'souq-app-project',
    databaseURL: 'https://souq-app-project-default-rtdb.asia-southeast1.firebasedatabase.app',
  storageBucket: 'souq-app-project.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIoS9JBjROZjeKI8SwV8M7_Db8dhVn4Xs',
    appId: '1:583163872183:web:6c6ce0d27e569f9ec39e32',
    messagingSenderId: '583163872183',
    projectId: 'souq-app-project',
    authDomain: 'souq-app-project.firebaseapp.com',
    databaseURL: 'https://souq-app-project-default-rtdb.asia-southeast1.firebasedatabase.app',
  storageBucket: 'souq-app-project.appspot.com',
    measurementId: 'G-TZD7LJ277F',
  );
}
